name: Node CI

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    name: Test pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Installing depedencies
        run: npm ci --production
      - name: eslint
        uses: icrawl/action-eslint@v1
      - name: Run unit tests
        run: npm test
      - name: Build the app
        run: npm run build
